name: vehicle-detection-0205
domain: Object Detection
problem: Vehicle Detection
framework: OTEDetection v2.1.0.1
summary: Vehicle Detection based on ResNet18+fpn+CascadeRCNN.
annotation_format: COCO
dependencies:
- sha256: TBD
  size: TBD
  source: https://download.01.org/opencv/openvino_training_extensions/models/object_detection/v2/vehicle-detection-0205.pth
  destination: snapshot.pth
- source: ../tools/train.py
  destination: train.py
- source: ../tools/eval.py
  destination: eval.py
- source: ../../../tools/export.py
  destination: export.py
- source: ../../../tools/quantize.py
  destination: quantize.py
- source: ../../../../../pytorch_toolkit/ote
  destination: packages/ote
- source: ../../../../object_detection/oteod
  destination: packages/oteod
- source: ../../requirements.txt
  destination: requirements.txt
max_nodes: 1
training_target:
- CPU
- GPU
inference_target:
- CPU
- iGPU
- VPU
hyper_parameters:
  basic:
    batch_size: 4
    base_learning_rate: 0.02
    epochs: 20
output_format:
  onnx:
    default: true
  openvino:
    default: true
    input_format: BGR
quantization: TBD
metrics:
- display_name: Size
  key: size
  unit: Mp
  value: 24.11
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 112.34
- display_name: AP @ [IoU=0.50:0.95]
  key: ap
  unit: '%'
  value: 43.8
training_gpu_num: 1
show_on_chart: True
