name: mobilenet_v2-2s_ssd-384x384
domain: Object Detection
framework: OTEDetection v2.1.0.1
summary: Custom Object Detection based on MobileNetV2 (SSD).
dependencies:
- sha256: 923647b5737f6fc5f08660cb43f509f718ce0a5e9abc66f611ffb057e8c60986
  size: 16164456
  source: https://download.01.org/opencv/openvino_training_extensions/models/object_detection/v2/mobilenet_v2-2s_ssd-384x384.pth
  destination: snapshot.pth
- source: ../tools/train.py
  destination: train.py
- source: ../tools/eval.py
  destination: eval.py
- source: ../../tools/export.py
  destination: export.py
- source: ../../tools/quantize.py
  destination: quantize.py
max_nodes: 1
hyper_parameters:
  batch_size: 64
  base_learning_rate: 0.05
  epochs: 0
export:
  onnx:
    enabled: true
  openvino:
    enabled: true
    input_format: BGR
quantization: TBD
metrics:
- display_name: Size
  key: size
  unit: Mp
  value: 1.99
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 1.92
- display_name: AP @ [IoU=0.50:0.95]
  key: ap
  unit: '%'
  value: 13.3
gpu_num: 3
config: config.py
