# See help here: https://github.com/marketplace/actions/labeler

dependencies:
  - '**/*requirements*.*'
  - '**/setup.py'
CLI:
  - 'ote_cli/*'
SDK:
  - 'ote_sdk/*'
tests:
  - 'tests/*'
tasks:
  - 'external/*'
