default_language_version:
    python: python3.8
files: "\
        ote_sdk"
repos:
-   repo: https://github.com/PyCQA/isort
    rev: '5.9.2'
    hooks:
    -   id: isort
        args: ["--settings", ".isort.cfg"]

-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black
        name: 'black'
        files: '^ote_sdk/.*\.py'

-   repo: https://github.com/PyCQA/flake8
    rev: '3.9.2'
    hooks:
    -   id: flake8
        name: 'flake8'
        files: '^ote_sdk/.*\.py'
        args: ["--config", ".flake8", "--max-complexity", "20"]
        exclude: ".*/protobuf"

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
    -   id: mypy
        name: 'mypy'
        files: '^ote_sdk/.*\.py'
        args: ["--config-file=ote_sdk/.mypy.ini"]
        additional_dependencies: [numpy==1.19.5, types-PyYAML, attrs==21.2.*, types-requests, types-Deprecated, types-docutils, types_futures, types-python-dateutil]

# -   repo: local
#     hooks:
#     -   id: pylint
#         name: 'pylint'
#         files: '^ote_sdk/.*\.py'
#         entry: tox --quiet --
#         language: system
#         types: [python]
