backbone_config:
  type: cnn
  output_channels: 80
head:
  type: LSTMEncoderDecoder
  encoder_input_size: 80
  reduction: weighted
  cnn_encoder_height: 12
  dropout_p: 0.5
val_transforms_list:
  - name: TransformGrayscale
  - name: TransformResizeNormalizePad
    target_height: 96
device: cuda
num_workers: 4
use_ctc: true
model_path: work_dir/model_checkpoints/accuracy_test_best_model_2021-12-15_12-51-21.pth
model_url: http://localhost:8000/accuracy_test_best_model_2021-12-15_12-51-21.pth
vocab_path: vocabs/vocab_gnhk.json
train:
  batch_size: 4
  learning_rate: 0.0003
  clip_grad: 2.0
  epochs: 300
  loss_type: CTC
  CTCLossZeroInf: true
  save_freq: 10000
  val_freq: 10000
  print_freq: 250
  optimizer: RMSprop
  save_dir: model_checkpoints
  whitespace: false # whether to insert spaces between characters
  acc_type: label_level_recognition_accuracy
  datasets:
    train:
      - type: LMDBDataset
        case_sensitive: true
        data_path: ../../../data/handwritten_text_recognition/gnhk-sample
        grayscale: true
        insert_whitespace: false
    validate:
      - type: LMDBDataset
        case_sensitive: true
        data_path: ../../../data/handwritten_text_recognition/gnhk-sample
        grayscale: true
        insert_whitespace: false
  train_transforms_list:
    - name: TransformGrayscale
    - name: TransformDataAugmentation
    - name: TransformResizeNormalizePad
      target_height: 96
eval:
  dataset:
    type: LMDBDataset
    case_sensitive: true
    data_path: ../../../data/handwritten_text_recognition/gnhk-sample
    grayscale: true
    insert_whitespace: false
  acc_type: label_level_recognition_accuracy
  whitespace: false
demo:
  transforms_list: []
export:
  whitespace: false
  acc_type: label_level_recognition_accuracy
  model_input_names: "actual_input"
  model_output_names: "output"
  scale_values: [127.5]
  mean_values: [127.5]
  res_model_name: handwritten-english-recognition-0001.onnx
  export_ir: true
  verbose_export: true
  input_shape:
    - 1
    - 1
    - 96
    - 2000
  openvino_transforms_list:
    - name: TransformGrayscale

