name: person-detection-0202
domain: Object Detection
framework: OTEDetection v2.1.0.1
summary: Person Detection based on MobileNetV2 (SSD).
dependencies:
- sha256: 65b6ac3c9250cf620206525ba3f2a341839ef722c57962441d1470caa2c26bb7
  size: 14905210
  source: https://download.01.org/opencv/openvino_training_extensions/models/object_detection/v2/person-detection-0202-1.pth
  destination: snapshot.pth
- source: ../tools/train.py
  destination: train.py
- source: ../tools/eval.py
  destination: eval.py
- source: ../../tools/export.py
  destination: export.py
- source: ../../tools/quantize.py
  destination: quantize.py
max_nodes: 1
training_target:
- CPU
- GPU
inference_target:
- CPU
- iGPU
- VPU
hyper_parameters:
  basic:
    batch_size: 30
    base_learning_rate: 0.05
    epochs: 20
export:
  onnx:
    enabled: true
  openvino:
    enabled: true
    input_format: BGR
quantization: TBD
metrics:
- display_name: Size
  key: size
  unit: Mp
  value: 1.83
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 3.28
- display_name: AP @ [IoU=0.50:0.95]
  key: ap
  unit: '%'
  value: 32.8
gpu_num: 2
config: config.py
