name: person-vehicle-bike-detection-2002
domain: Object Detection
framework: OTEDetection v2.1.0.1
summary: Person Vehicle Bike Detection based on MobileNetV2 (SSD).
dependencies:
- sha256: 23d2ba1282bc1a0072e9d9737f969c1becab51bc65b235ca586a22756e260a91
  size: 14937174
  source: https://download.01.org/opencv/openvino_training_extensions/models/object_detection/v2/vehicle-person-bike-detection-2002-1.pth
  destination: snapshot.pth
- source: ../tools/train.py
  destination: train.py
- source: ../tools/eval.py
  destination: eval.py
- source: ../../tools/export.py
  destination: export.py
- source: ../../tools/quantize.py
  destination: quantize.py
max_nodes: 1
hyper_parameters:
  batch_size: 30
  base_learning_rate: 0.05
  epochs: 20
export:
  onnx:
    enabled: true
  openvino:
    enabled: true
    input_format: BGR
quantization: TBD
metrics:
- display_name: Size
  key: size
  unit: Mp
  value: 1.84
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 3.3
- display_name: mAP @ [IoU=0.50:0.95]
  key: map
  unit: '%'
  value: 24.8
gpu_num: 4
config: config.py
