name: face-detection-0204
domain: Object Detection
framework: OTEDetection v2.1.0.1
summary: Face Detection based on MobileNetV2 (SSD).
annotation_format: COCO
dependencies:
- sha256: 7a227579f8ebc9017a742ed66b3a9bdc3582090a1c06c9ccbf84722b4a2ffad2
  size: 14904360
  source: https://download.01.org/opencv/openvino_training_extensions/models/object_detection/v2/face-detection-0204.pth
  destination: snapshot.pth
- source: ../tools/train.py
  destination: train.py
- source: ../tools/eval.py
  destination: eval.py
- source: ../../../tools/export.py
  destination: export.py
- source: ../../../tools/quantize.py
  destination: quantize.py
- source: ../../../../../pytorch_toolkit/ote
  destination: ote
- source: ../../../../object_detection/oteod
  destination: oteod
- source: ../../requirements.txt
  destination: requirements.txt
max_nodes: 1
training_target:
- CPU
- GPU
inference_target:
- CPU
- iGPU
- VPU
hyper_parameters:
  basic:
    batch_size: 32
    base_learning_rate: 0.05
    epochs: 70
output_format:
  onnx:
    default: true
  openvino:
    default: true
    input_format: BGR
quantization: TBD
metrics:
- display_name: AP @ [IoU=0.50:0.95]
  key: ap
  unit: '%'
  value: 21.4
- display_name: AP for faces > 64x64
  key: ap_64x64
  unit: '%'
  value: 92.888
- display_name: WiderFace Easy
  key: widerface_e
  unit: '%'
  value: 90.453
- display_name: WiderFace Medium
  key: widerface_m
  unit: '%'
  value: 85.448
- display_name: WiderFace Hard
  key: widerface_h
  unit: '%'
  value: 52.091
- display_name: Size
  key: size
  unit: Mp
  value: 1.83
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 2.52
gpu_num: 4
config: model.py
estimated_batch_time: 1.0
