name: horizontal-text-detection-0001
domain: Object Detection
framework: OTEDetection v2.1.0.1
summary: Text Detection based on MobileNetV2 (FCOS).
annotation_format: COCO
dependencies:
- sha256: ac879a21e3558b5d516f04e76444e697553309873908e45a6fa67fc5dda397f9
  size: 15825821
  source: https://download.01.org/opencv/openvino_training_extensions/models/object_detection/v2/horizontal-text-detection-0001.pth
  destination: snapshot.pth
- source: ../tools/train.py
  destination: train.py
- source: ../tools/eval.py
  destination: eval.py
- source: ../../tools/export.py
  destination: export.py
- source: ../../tools/quantize.py
  destination: quantize.py
max_nodes: 1
training_target:
- CPU
- GPU
inference_target:
- CPU
- iGPU
- VPU
hyper_parameters:
  basic:
    batch_size: 8
    base_learning_rate: 0.01
    epochs: 25
output_format:
  onnx:
    default: true
  openvino:
    default: true
    input_format: BGR
quantization: TBD
metrics:
- display_name: Size
  key: size
  unit: Mp
  value: 1.95
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 8.0
- display_name: F1-score
  key: f1
  unit: '%'
  value: 88.45
- display_name: Recall
  key: recall
  unit: '%'
  value: 86.39
- display_name: Precision
  key: precision
  unit: '%'
  value: 90.61
- display_name: AP @ [IoU=0.50:0.95]
  key: ap
  unit: '%'
  value: 52.4
gpu_num: 2
config: config.py
estimated_batch_time: 1.0
