name: human-pose-estimation-0005
domain: Pose Estimation
problem: COCO Human Pose Estimation
framework: OTEPose v0.12.0
summary: Multi person pose estimation based on EfficientHRNet architecture.
annotation_format: COCO
initial_weights: snapshot.pth
dependencies:
# TODO.
- sha256: a1f839ac6def3168025ad2638f670850857fe1c825f17d8b045f17a70afa8472
  size: 101353681
  source: /tmp/weights.pth
  destination: snapshot.pth
- source: ../../../../../ote/tools/train.py
  destination: train.py
- source: ../../../../../ote/tools/eval.py
  destination: eval.py
- source: ../../../../../ote/tools/export.py
  destination: export.py
- source: ../../../../../ote/tools/compress.py
  destination: compress.py
- source: ../../../../../ote
  destination: packages/ote
- source: ../../requirements.txt
  destination: requirements.txt
dataset_requirements: ~
max_nodes: 1
training_target:
- GPU
inference_target:
- CPU
hyper_parameters:
  basic:
    batch_size: 14
    base_learning_rate: 0.001
    epochs: 300
output_format:
  onnx:
    default: true
  openvino:
    default: true
    input_format: BGR
optimisations: ~
metrics:
- display_name: Size
  key: size
  unit: Mp
  value: 8.84
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 6.04
- display_name: AP @ [IoU=0.50:0.95]
  key: mAP
  unit: '%'
  value: 45.5
gpu_num: 2
config: model.py
tensorboard: true
estimated_batch_time: -1
