name: face-detection-0202
description: Face Detection based on MobileNetV2 (SSD).
dependencies:
- sha256: 774ad73bd1529c4f54867f35d18db00ddc896e6586be89b0b1ed4b0c5161051e
  size: 14904301
  source: https://download.01.org/opencv/openvino_training_extensions/models/object_detection/v2/face-detection-0202.pth
  destination: snapshot.pth
- source: ../tools/train.py
  destination: train.py
- source: ../tools/eval.py
  destination: eval.py
- source: ../../tools/export.py
  destination: export.py
- source: ../../tools/quantize.py
  destination: quantize.py
training_parameters:
  gpu_num: 2
  batch_size: 65
  base_learning_rate: 0.05
  epochs: 70
metrics:
- display_name: AP @ [IoU=0.50:0.95]
  key: ap
  unit: '%'
  value: 20.3
- display_name: AP for faces > 64x64
  key: ap_64x64
  unit: '%'
  value: 91.938
- display_name: WiderFace Easy
  key: widerface_e
  unit: '%'
  value: 89.382
- display_name: WiderFace Medium
  key: widerface_m
  unit: '%'
  value: 83.919
- display_name: WiderFace Hard
  key: widerface_h
  unit: '%'
  value: 50.189
- display_name: Size
  key: size
  unit: Mp
  value: 1.83
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 1.84
config: config.py
