train:
  backbone_config:
    arch: resnext101_32x8d
    disable_layer_3: true
    disable_layer_4: true
  batch_size: 4
  device: cuda
  learning_rate: 0.000001
  log_path: logs
  model_path: model_checkpoints/model.pth
  optimizer: Adam
  save_dir: model_checkpoints
  train_paths:
    - datasets/sample_medium_dataset
  val_path: datasets/sample_medium_dataset
  vocab_path: datasets/sample_medium_dataset/vocab.pkl
eval:
  backbone_config:
    arch: resnext101_32x8d
    disable_layer_3: true
    disable_layer_4: true
  device: cuda
  model_path: model_checkpoints/medium_0169.pth
  val_path: datasets/sample_medium_dataset
  vocab_path: datasets/sample_medium_dataset/vocab.pkl
  split_file: validate
  target_metric: 0.99
demo:
  backbone_config:
    arch: resnext101_32x8d
    disable_layer_3: true
    disable_layer_4: true
  device: cuda
  transforms_list:
    - name: "TransformCropPad"
      target_shape:
        - 50
        - 950
  input_images:
    - datasets/sample_medium_dataset/images_processed/1.png
  model_path: model_checkpoints/medium_0169.pth
  val_path: datasets/sample_medium_dataset
  vocab_path: datasets/sample_medium_dataset/vocab.pkl
  map_location: cuda
export:
  backbone_config:
    arch: resnext101_32x8d
    disable_layer_3: true
    disable_layer_4: true
  dummy_input: datasets/sample_medium_dataset/images_processed/1.png
  model_path: model_checkpoints/medium_0169.pth
  vocab_path: datasets/sample_medium_dataset/vocab.pkl
  res_encoder_name: medium_v2_encoder.onnx
  res_decoder_name: medium_v2_decoder.onnx
  export_ir: true
  verbose_export: false
  input_shape_decoder:
    - 1
    - 3
    - 50
    - 950
  transforms_list:
    - name: "TransformCropPad"
      target_shape:
        - 50
        - 950
