backbone_config:
  arch: resnext101_32x8d
  disable_layer_3: true
  disable_layer_4: true
backbone_type: resnet
device: cuda
transforms_list:
  - name: "BatchCropPadToTGTShape"
    target_shape:
      - 50
      - 950
input_images:
- datasets/sample_medium_dataset/images_processed/1.png
model_path: model_checkpoints/medium_0169.pth
old_model: true
val_path: datasets/sample_medium_dataset
vocab_path: datasets/sample_medium_dataset/vocab.pkl
map_location: cuda
