backbone_config:
  arch: resnet50
  disable_layer_3: true
  disable_layer_4: true
  enable_last_conv: false
  in_lstm_ch: 64
backbone_type: resnet50
device: cuda
head:
  beam_width: 0
  dec_rnn_h: 512
  emb_size: 80
  enc_rnn_h: 256
  in_lstm_ch: 512
  max_len: 256
  n_layer: 1
input_images:
- /home/loginov/1
- /home/loginov/2
model_path: /home/vloginov/work/im2latex/medium_v2/save_dir/model_epoch_1_step_4000_2020-09-10_17-57-51.pth
val_path: /home/vloginov/work/im2latex/medium_v2/
vocab_path: /home/vloginov/work/im2latex/medium_v2/vocab.pkl
