backbone_config:
  arch: resnext101_32x8d
  disable_layer_3: true
  disable_layer_4: true
backbone_type: resnet
batch_size: 1
device: cuda
model_path: model_checkpoints/model.pth
val_path: datasets/sample_medium_dataset
vocab_path: datasets/sample_medium_dataset/vocab.pkl
old_model: true
split_file: validate
target_metric: 0.99