backbone_config:
  arch: resnext101_32x8d
  disable_layer_3: true
  disable_layer_4: true
backbone_type: resnet
dummy_input: datasets/sample_medium_dataset/images_processed/1.png
model_path: model_checkpoints/medium_0169.pth
vocab_path: datasets/sample_medium_dataset/vocab.pkl
res_encoder_name: medium_v2_encoder.onnx
res_decoder_name: medium_v2_decoder.onnx
old_model: true
export_ir: true
verbose_export: true
input_shape_decoder:
  - 1
  - 3
  - 50
  - 950
transforms_list:
  - name: "BatchCropPadToTGTShape"
    target_shape:
      - 50
      - 950
encoder_input_names: "imgs"
encoder_output_names: "row_enc_out,hidden,context,init_0"
decoder_input_names: "dec_st_h,dec_st_c,output_prev,row_enc_out,tgt"
decoder_output_names: "dec_st_h_t,dec_st_c_t,output,logit"