backbone_config:
  arch: resnext101_32x8d
  disable_layer_3: true
  disable_layer_4: true
  enable_last_conv: false
  in_lstm_ch: 512
backbone_type: resnet
head:
  beam_width: 0
  dec_rnn_h: 512
  emb_size: 80
  encoder_hidden_size: 256
  in_lstm_ch: 512
  max_len: 256
  n_layer: 1
dummy_input: /home/vloginov/work/im2latex/medium_v2/images_processed/1269.png
model_path: /media/cluster_fs/user/vloginov/im2latex_project/0169/models/accuracy_best_model_2020-04-23_08-01-13
vocab_path: /home/vloginov/work/im2latex/medium_v2/vocab.pkl
res_encoder_name: medium_v2_encoder.onnx
res_decoder_name: medium_v2_decoder.onnx
old_model: true
export_ir: true
verbose_export: true
input_shape_decoder:
  - 1
  - 3
  - 40
  - 1100
transforms_list:
  - name: "BatchCropPadToTGTShape"
    target_shape:
      - 40
      - 1100
encoder_input_names: "imgs"
encoder_output_names: "row_enc_out,hidden,context,init_0"
decoder_input_names: "dec_st_h,dec_st_c,output_prev,row_enc_out,tgt"
decoder_output_names: "dec_st_h_t,dec_st_c_t,output,logit"