common:
  backbone_config:
    arch: resnext50_32x4d
    disable_layer_3: false
    disable_layer_4: true
    output_channels: 1024
  head:
    encoder_input_size: 1024
  model_path: model_checkpoints/polynomials_handwritten_0166.pth
  device: cuda
  vocab_path: vocabs/vocab_handwritten_polynomials.json
train:
  batch_size: 4
  learning_rate: 0.000001
  log_path: logs
  optimizer: Adam
  save_dir: model_checkpoints
  train_paths:
    - ../../data/formula_recognition/sample_handwritten_polynomials
  val_path: ../../data/formula_recognition/sample_handwritten_polynomials
eval:
  val_path: ../../data/formula_recognition/sample_handwritten_polynomials
  split_file: validate
  target_metric: 0.8
demo:
  input_images:
    - ../../data/formula_recognition/sample_handwritten_polynomials/
export:
  res_encoder_name: handwritten_polynoms_encoder.onnx
  res_decoder_name: handwritten_polynoms_decoder.onnx
  export_ir: true
  verbose_export: false
  input_shape_decoder:
    - 1
    - 3
    - 96
    - 1024
