backbone_config:
  arch: resnext50_32x4d
  disable_layer_3: true
  disable_layer_4: true
backbone_type: resnet
batch_size: 4
device: cuda
learning_rate: 0.000001
log_path: logs
model_path: model_checkpoints/model.pth
optimizer: Adam
save_dir: model_sheckpoints
train_paths:
- datasets/sample_medium_dataset
val_path: datasets/sample_medium_dataset
vocab_path: datasets/sample_medium_dataset/vocab.pkl
old_model: true
