name: mobilenet_v2-2s_ssd-256x256
summary: Custom Object Detection based on MobileNetV2 (SSD).
dependencies:
- sha256: 4a7b491b5fd45ee6ee760e910a8f9a38768be79ccdeb85a1fb3ae4e4c3dd677f
  size: 16164483
  source: https://download.01.org/opencv/openvino_training_extensions/models/object_detection/v2/mobilenet_v2-2s_ssd-256x256.pth
  destination: snapshot.pth
- source: ../tools/train.py
  destination: train.py
- source: ../tools/eval.py
  destination: eval.py
- source: ../../tools/export.py
  destination: export.py
- source: ../../tools/quantize.py
  destination: quantize.py
hyper_parameters:
  batch_size: 64
  base_learning_rate: 0.05
  epochs: 0
export:
  onnx:
    enabled: true
  openvino:
    enabled: true
    input_format: BGR
quantization: TBD
metrics:
- display_name: Size
  key: size
  unit: Mp
  value: 1.99
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 0.86
- display_name: AP @ [IoU=0.50:0.95]
  key: ap
  unit: '%'
  value: 11.3
gpu_num: 3
config: config.py
