name: person-vehicle-bike-detection-2000
domain: Object Detection
framework: OTEDetection v2.1.0.1
summary: Person Vehicle Bike Detection based on MobileNetV2 (SSD).
annotation_format: COCO
dependencies:
- sha256: b586ec8ba828ebfc77765ca16849bb1d17b771713bb89373531d2847e7c08d28
  size: 14937195
  source: https://download.01.org/opencv/openvino_training_extensions/models/object_detection/v2/vehicle-person-bike-detection-2000-1.pth
  destination: snapshot.pth
- source: ../tools/train.py
  destination: train.py
- source: ../tools/eval.py
  destination: eval.py
- source: ../../tools/export.py
  destination: export.py
- source: ../../tools/quantize.py
  destination: quantize.py
max_nodes: 1
training_target:
- CPU
- GPU
inference_target:
- CPU
- iGPU
- VPU
hyper_parameters:
  basic:
    batch_size: 192
    base_learning_rate: 0.05
    epochs: 20
output_format:
  onnx:
    default: true
  openvino:
    default: true
    input_format: BGR
quantization: TBD
metrics:
- display_name: Size
  key: size
  unit: Mp
  value: 1.84
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 0.82
- display_name: mAP @ [IoU=0.50:0.95]
  key: map
  unit: '%'
  value: 16.5
gpu_num: 4
config: config.py
estimated_batch_time: 1.0
