name: person-vehicle-bike-detection-2002
domain: Object Detection
framework: OTEDetection v2.1.0.1
summary: Person Vehicle Bike Detection based on MobileNetV2 (SSD).
annotation_format: COCO
dependencies:
- sha256: 23d2ba1282bc1a0072e9d9737f969c1becab51bc65b235ca586a22756e260a91
  size: 14937174
  source: https://download.01.org/opencv/openvino_training_extensions/models/object_detection/v2/vehicle-person-bike-detection-2002-1.pth
  destination: snapshot.pth
- source: ../tools/train.py
  destination: train.py
- source: ../tools/eval.py
  destination: eval.py
- source: ../../../tools/export.py
  destination: export.py
- source: ../../../tools/quantize.py
  destination: quantize.py
- source: ../../../../../pytorch_toolkit/ote
  destination: ote
- source: ../../../../object_detection/oteod
  destination: oteod
- source: ../../requirements.txt
  destination: requirements.txt
max_nodes: 1
training_target:
- CPU
- GPU
inference_target:
- CPU
- iGPU
- VPU
hyper_parameters:
  basic:
    batch_size: 30
    base_learning_rate: 0.05
    epochs: 20
output_format:
  onnx:
    default: true
  openvino:
    default: true
    input_format: BGR
quantization: TBD
metrics:
- display_name: Size
  key: size
  unit: Mp
  value: 1.84
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 3.3
- display_name: mAP @ [IoU=0.50:0.95]
  key: map
  unit: '%'
  value: 24.8
gpu_num: 4
config: model.py
estimated_batch_time: 1.0
