name: person-detection-0201
summary: Person Detection based on MobileNetV2 (SSD).
dependencies:
- sha256: 8258402480b714cd113493ba43c7ba6436e77d29cb9397f276ba11668fe18aa4
  size: 14905192
  source: https://download.01.org/opencv/openvino_training_extensions/models/object_detection/v2/person-detection-0201-1.pth
  destination: snapshot.pth
- source: ../tools/train.py
  destination: train.py
- source: ../tools/eval.py
  destination: eval.py
- source: ../../tools/export.py
  destination: export.py
- source: ../../tools/quantize.py
  destination: quantize.py
hyper_parameters:
  batch_size: 84
  base_learning_rate: 0.05
  epochs: 20
export:
  onnx:
    enabled: true
  openvino:
    enabled: true
    input_format: BGR
quantization: TBD
metrics:
- display_name: Size
  key: size
  unit: Mp
  value: 1.83
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 1.84
- display_name: AP @ [IoU=0.50:0.95]
  key: ap
  unit: '%'
  value: 29.9
gpu_num: 4
config: config.py
