name: mobilenet_v2-2s_ssd-384x384
domain: Object Detection
framework: OTEDetection v2.1.0.1
summary: Custom Object Detection based on MobileNetV2 (SSD).
annotation_format: COCO
classes: []
dependencies:
- sha256: 923647b5737f6fc5f08660cb43f509f718ce0a5e9abc66f611ffb057e8c60986
  size: 16164456
  source: https://download.01.org/opencv/openvino_training_extensions/models/object_detection/v2/mobilenet_v2-2s_ssd-384x384.pth
  destination: snapshot.pth
- source: ../tools/train.py
  destination: train.py
- source: ../tools/eval.py
  destination: eval.py
- source: ../../../tools/export.py
  destination: export.py
- source: ../../../tools/quantize.py
  destination: quantize.py
- source: ../../../../../pytorch_toolkit/ote
  destination: ote
- source: ../../../../object_detection/oteod
  destination: oteod
- source: ../../requirements.txt
  destination: requirements.txt
max_nodes: 1
training_target:
- CPU
- GPU
inference_target:
- CPU
- iGPU
- VPU
hyper_parameters:
  basic:
    batch_size: 64
    base_learning_rate: 0.05
    epochs: 15
output_format:
  onnx:
    default: true
  openvino:
    default: true
    input_format: BGR
quantization: TBD
metrics:
- display_name: Size
  key: size
  unit: Mp
  value: 1.99
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 1.92
- display_name: AP @ [IoU=0.50:0.95]
  key: ap
  unit: '%'
  value: 13.3
gpu_num: 3
config: config.py
estimated_batch_time: 1.0
