# Description.
model_template_id: ote_anomaly_segmentation_padim
name: PADIM
task_type: ANOMALY_SEGMENTATION
task_family: VISION
instantiation: "CLASS"
summary: PADIM with ResNet-18 backbone
application: ~

# Algo backend.
framework: OTEAnomalySegmentation v0.1.0

# Task implementations.
entrypoints:
  base: ote_anomalib.AnomalyTask
  openvino: ote_anomalib.OpenVINOAnomalyClassificationTask

# Hyper Parameters
hyper_parameters:
  base_path: ./configuration.yaml

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Computational Complexity
gigaflops: 3.9
size: 168.4
